# Generated by Django 4.1.7 on 2023-04-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendcore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField()),
                ('password', models.TextField()),
                ('contact', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
