# Generated by Django 4.2 on 2023-04-25 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendcore', '0004_forumpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forumpost',
            old_name='author',
            new_name='user_id',
        ),
    ]
