# Generated by Django 4.2 on 2023-04-26 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendcore', '0007_rename_post_comment_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendcore.forumpost'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
