# Generated by Django 4.2 on 2023-04-29 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendcore', '0009_marketplacepost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
